export const FORMATION_POSITIONS: Record<
  Lineup.Formations,
  Lineup.PositionValues[]
> = {
  ["4-2-3-1"]: [
    "center",
    "left",
    "center-left",
    "center-right",
    "right",
    "center-left",
    "center-right",
    "center-left-3",
    "center",
    "center-right-3",
    "center",
  ],
  ["3-4-1-2"]: [
    "center",
    "center-left-3",
    "center",
    "center-right-3",
    "left",
    "center-left",
    "center-right",
    "right",
    "center",
    "center-left",
    "center-right",
  ],
  ["4-4-2"]: [
    "center",
    "left",
    "center-left",
    "center-right",
    "right",
    "left",
    "center-left",
    "center-right",
    "right",
    "center-left",
    "center-right",
  ],
};

export const FORMATION_LAYERS: Record<Lineup.Formations, [number, number][]> = {
  ["4-2-3-1"]: [
    [0, 1],
    [1, 5],
    [5, 7],
    [7, 10],
    [10, 11],
  ],
  ["3-4-1-2"]: [
    [0, 1],
    [1, 4],
    [4, 8],
    [8, 9],
    [9, 11],
  ],
  ["4-4-2"]: [
    [0, 1],
    [1, 5],
    [5, 9],
    [9, 11],
  ],
};
export const FORMATION_POSITION_NAMES: Record<Lineup.Formations, string[]> = {
  ["4-2-3-1"]: [
    "GK",
    "Left Back",
    "Center Back (L)",
    "Center Back (R)",
    "Right Back",
    "Center Midfield (L)",
    "Center Midfield (R)",
    "Left Wing",
    "Center Attacking Midfield",
    "Right Wing",
    "Forward",
  ],
  ["3-4-1-2"]: [
    "GK",
    "CB (Left)",
    "CB",
    "CB (Right)",
    "Left Wing Back",
    "Center Midfield (Left)",
    "Center Midfield (Right)",
    "Right Wing Back",
    "CAM",
    "Forward (Left)",
    "Forward (Right)",
  ],
  ["4-4-2"]: [],
};
